### ISSUE TITLE
Script fails due to error

### ISSUE THREAD

**Issue by Legionivo** [gryf/slack-backup#1]
Hi! I've tried to use your script, but it fails for some reason. Can you take a look at error log below and fix it? @gryf 
```

2017-08-05 14:39:20,567 INFO: Skipping message from `kotlyar' since it's empty
Traceback (most recent call last):
  File "/home/odmin/myenv/lib/python3.5/site-packages/slack_backup/client.py", line 152, in _create_message
    filter(o.User.slackid == data['user']).one()
KeyError: 'user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odmin/myenv/bin/slack-backup", line 10, in <module>
    command.main()
  File "/home/odmin/myenv/lib/python3.5/site-packages/slack_backup/command.py", line 118, in main
    args.func(args)
  File "/home/odmin/myenv/lib/python3.5/site-packages/slack_backup/command.py", line 39, in fetch_data
    slack.update()
  File "/home/odmin/myenv/lib/python3.5/site-packages/slack_backup/client.py", line 53, in update
    self.update_history()
  File "/home/odmin/myenv/lib/python3.5/site-packages/slack_backup/client.py", line 132, in update_history
    self._create_message(msg, channel)
  File "/home/odmin/myenv/lib/python3.5/site-packages/slack_backup/client.py", line 155, in _create_message
    filter(o.User.slackid == data['comment']['user']).one()
KeyError: 'comment'

```

**Comment by gryf** [comment]
Looking at [slack API docs](https://api.slack.com/methods/channels.history), I see, that there could be messages without user defined at all - possibly messages generated by slack itself, or by bots with special messages types different than `message`. Funny, that I didn't bump on such messages, even I'm doing backups in weekly basis…

Anyway, I'll post patch soon, stay tuned.

**Comment by gryf** [comment]
@Legionivo, please, see if version 0.5 will resolve your issue.

**Comment by Legionivo** [comment]
@gryf 
Hi! Now it fails with another error

`2017-08-06 11:12:12,786 INFO: Update channel `xorjobs' information in DB
2017-08-06 11:12:12,918 INFO: Fetching and storing messages in DB
2017-08-06 11:12:12,923 INFO: Getting messages for channel `automation'
Traceback (most recent call last):
  File "/home/odmin/myenv/bin/slack-backup", line 10, in <module>
    command.main()
  File "/home/odmin/myenv/lib/python3.5/site-packages/slack_backup/command.py", line 118, in main
    args.func(args)
  File "/home/odmin/myenv/lib/python3.5/site-packages/slack_backup/command.py", line 39, in fetch_data
    slack.update()
  File "/home/odmin/myenv/lib/python3.5/site-packages/slack_backup/client.py", line 53, in update
    self.update_history()
  File "/home/odmin/myenv/lib/python3.5/site-packages/slack_backup/client.py", line 132, in update_history
    self._create_message(msg, channel)
  File "/home/odmin/myenv/lib/python3.5/site-packages/slack_backup/client.py", line 156, in _create_message
    filter(o.User.slackid == data['user']).one()
  File "/home/odmin/myenv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2820, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
`

**Comment by gryf** [comment]
Do you have any users populated in the db? It's kind of strange, that you don't have particular user in a database, while you get the identifier within data returned from slack api… I'm afraid, that without the actual data I can't do much more.

You can add at line 150 of [client.py](https://github.com/gryf/slack-backup/blob/64d4b094683b9c789dd1c880d488ae398324a765/slack_backup/client.py#L150) lines, like below:
```python
        import json
        logging.debug('Message data: %s', json.dumps(data))
```
and run fetch with additional `-vv` parameter to see which message is causing the error. If thre is an `user` field there (it will be an identifier, an alphannumeric value which is starting from capital u, for example `U34P4DPHQ`), and check if such user exists in your team (using an [api test](https://api.slack.com/methods/users.list/test)).

**Comment by Legionivo** [comment]
One of users was recently deactivated. Can it be the root cause?

**Comment by gryf** [comment]
If such user isn't listed in `user.list` call, than it's an issue on Slack API side, since there are no restriction in fetching user data in slack-backup code - all users are kept, regardless they are deleted or not. According to the [Slack API docs](https://api.slack.com/methods/users.list), `user.list` method should return all users:

> Lists all users in a Slack team.
> This method returns a list of all users in the team. This includes deleted/deactivated users.

**Comment by gryf** [comment]
Could you please check, if deactivated user shows up using [api test page](https://api.slack.com/methods/users.list/test)? If not, than there are two ways to proceed:

1. Either you'll report defect on Slack somehow
2. I can add an workaround for such cases, with two possibilities:
    * slack-backup will ignore messages for unknown senders,
    * or there would be created some phantom account for all unknown users
    * or there would be separate phantom user for every each unknown users.

Although, I think it is an issue with your particular case, or general error with deleted/deactivated users on Slack side.

**Comment by dtenenba** [comment]
I have the same error as in the original post in this issue, with slack-backup 0.6 and python 3.4.

```
Traceback (most recent call last):
  File "/fh/fast/_ADM/SciComp/svcacct/envs/slack-backup/lib/python3.4/site-packages/slack_backup/client.py", line 159, in _create_message
    filter(o.User.slackid == data['user']).one()
KeyError: 'user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/fh/fast/_ADM/SciComp/svcacct/envs/slack-backup/bin/slack-backup", line 10, in <module>
    command.main()
  File "/fh/fast/_ADM/SciComp/svcacct/envs/slack-backup/lib/python3.4/site-packages/slack_backup/command.py", line 141, in main
    args.func(args)
  File "/fh/fast/_ADM/SciComp/svcacct/envs/slack-backup/lib/python3.4/site-packages/slack_backup/command.py", line 62, in fetch_data
    slack.update()
  File "/fh/fast/_ADM/SciComp/svcacct/envs/slack-backup/lib/python3.4/site-packages/slack_backup/client.py", line 54, in update
    self.update_history()
  File "/fh/fast/_ADM/SciComp/svcacct/envs/slack-backup/lib/python3.4/site-packages/slack_backup/client.py", line 133, in update_history
    self._create_message(msg, channel)
  File "/fh/fast/_ADM/SciComp/svcacct/envs/slack-backup/lib/python3.4/site-packages/slack_backup/client.py", line 162, in _create_message
    filter(o.User.slackid == data['comment']['user']).one()
KeyError: 'comment'
```

**Comment by gryf** [comment]
If this behaviour bothers you, @dtenenba , just make another issue and help me choose appropriate way for handle that. You can judge that by examining a message body, which should be displayed in the log (if your log level is low enough). I still didn't bump on such issue.
