### ISSUE TITLE
python type error

### ISSUE THREAD

**Issue by ajRiverav** [gryf/slack-backup#10]
This occurred while running the slack-backup script ver 0.7.

```
Traceback (most recent call last):
  File "/Users/user/myenv/bin/slack-backup", line 10, in <module>
    command.main()
  File "/Users/user/myenv/lib/python3.7/site-packages/slack_backup/command.py", line 143, in main
    args.func(args)
  File "/Users/user/myenv/lib/python3.7/site-packages/slack_backup/command.py", line 62, in fetch_data
    slack.update()
  File "/Users/user/myenv/lib/python3.7/site-packages/slack_backup/client.py", line 74, in update
    self.update_history()
  File "/Users/user/myenv/lib/python3.7/site-packages/slack_backup/client.py", line 166, in update_history
    self._create_message(msg, channel)
  File "/Users/user/myenv/lib/python3.7/site-packages/slack_backup/client.py", line 275, in _create_message
    self._file_data(message, data['item'])
  File "/Users/user/myenv/lib/python3.7/site-packages/slack_backup/client.py", line 304, in _file_data
    message.file.filepath = self.downloader.download(priv_url, 'file')
  File "/Users/user/myenv/lib/python3.7/site-packages/slack_backup/download.py", line 88, in download
    shutil.move(temp_file, filepath)
  File "/Users/user/myenv/lib/python3.7/shutil.py", line 546, in move
    if os.path.isdir(dst):
  File "/Users/user/myenv/bin/../lib/python3.7/genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Comment by ajRiverav** [comment]
This issue may still persist, but I found a way around it.
